### ISSUE TITLE
Clean up/rename

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/common-utils#25]
Do we really the interface definition here? Pros/cons from technical and conceptiual point of view?

Currently, this repo is highly non-intuitive. What does it do? Why does a `coord-env-interface` repo contain mostly baseline algorithms?

Should we throw out the interface part and just keep dummy algo and environment? And rename the repo accordingly?

**Comment by adnan904** [comment]
All the repos have been updated to work with the common-utils repo. Closing the issue.
